
export const languageCodes={
    "Afrikaans (Afrikaans)": "af",
    "العربية (Arabic)": "ar",
    "български (Bulgarian)": "bg",
    "বাংলা (Bengali)": "bn",
    "Català (Catalan)": "ca",
    "Čeština (Czech)": "cs",
    "Dansk (Danish)": "da",
    "Deutsch (German)": "de",
    "Ελληνικά (Greek)": "el",
    "English (English)": "en",
    "Español (Spanish)": "es",
    "Eesti (Estonian)": "et",
    "فارسی (Persian)": "fa",
    "Suomi (Finnish)": "fi",
    "Français (French)": "fr",
    "ગુજરાતી (Gujarati)": "gu",
    "עברית (Hebrew)": "he",
    "हिन्दी (Hindi)": "hi",
    "Hrvatski (Croatian)": "hr",
    "Magyar (Hungarian)": "hu",
    "Bahasa Indonesia (Indonesian)": "id",
    "Italiano (Italian)": "it",
    "日本語 (Japanese)": "ja",
    "ಕನ್ನಡ (Kannada)": "kn",
    "한국어 (Korean)": "ko",
    "Lietuvių (Lithuanian)": "lt",
    "Latviešu (Latvian)": "lv",
    "മലയാളം (Malayalam)": "ml",
    "मराठी (Marathi)": "mr",
    "Bahasa Melayu (Malay)": "ms",
    "Nederlands (Dutch)": "nl",
    "Norsk (Norwegian)": "no",
    "Polski (Polish)": "pl",
    "Português (Portuguese)": "pt",
    "Română (Romanian)": "ro",
    "Русский (Russian)": "ru",
    "Slovenčina (Slovak)": "sk",
    "Slovenščina (Slovenian)": "sl",
    "Српски (Serbian)": "sr",
    "Svenska (Swedish)": "sv",
    "Kiswahili (Swahili)": "sw",
    "தமிழ் (Tamil)": "ta",
    "తెలుగు (Telugu)": "te",
    "ไทย (Thai)": "th",
    "Türkçe (Turkish)": "tr",
    "Українська (Ukrainian)": "uk",
    "اردو (Urdu)": "ur",
    "Tiếng Việt (Vietnamese)": "vi",
    "中文 (Chinese)": "zh"
}

